version: '2'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sicred
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

#  sicredapi:
#    image: sicredapi:latest
#    container_name: sicredapi
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    links:
#      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

volumes:
  postgres-data: